title: "My Portfolio"
description: "Labs, walkthroughs, write-ups, and demos"
url: "https://andrewrhoden.github.io"
baseurl: ""  # Leave empty for root domain

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
