 title: "My Cybersecurity and IT Portfolio"
description: "Labs, walkthroughs, write-ups, and hands-on demos"
url: "https://andrewrhoden.github.io"
baseurl: ""  # Leave empty for user/organization site

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

# Optional: some theme enhancements
markdown: kramdown
kramdown:
  input: GFM
